import type { Metadata } from 'next'
import { headers } from 'next/headers'
import { notFound } from 'next/navigation'
import { Nav } from '@/components/layout/nav'
import { PostView } from '@/components/blog/post-view'
import { getPostBySlug } from '@/lib/posts'
import { getImagesByIds } from '@/lib/images'
import { resolveRegion } from '@/lib/geo'
import type { Block } from '@/lib/blog-schema'
import { articleSchema, breadcrumbSchema, faqPageSchema, howToSchema, speakableSchema } from '@/lib/seo'

interface BlogPostPageProps {
  params: Promise<{ slug: string }>
}

// Same revalidate window as the index — see PRD §5.4.
export const revalidate = 60

export async function generateMetadata({ params }: BlogPostPageProps): Promise<Metadata> {
  const { slug } = await params
  const region = resolveRegion(await headers())
  const post = await getPostBySlug(slug, region)
  if (!post) return { title: 'Not found', robots: { index: false, follow: false } }

  const title = post.meta_title ?? post.title
  const description = post.meta_description ?? post.excerpt ?? undefined
  // Canonical URL is always the base — geo variants share one URL per
  // PRD §5.6 (avoids SEO duplication). When canonical_url is set it can
  // point at an external syndication target, so the markdown alternate
  // is anchored to our own origin (the raw.md route only exists here).
  const canonical = post.canonical_url ?? `https://www.metaborong.com/blog/${post.slug}/`
  const markdownAlternate = `https://www.metaborong.com/blog/${post.slug}/raw.md`

  // M5-core: every published post gets a dynamic OG card via /og?slug=…
  // (1200×630 PNG generated by app/og/route.tsx). Cover image uploads
  // could replace this later, but the route is the v1 default so no
  // post ever shares without a card.
  const ogImage = `https://www.metaborong.com/og?slug=${encodeURIComponent(post.slug)}`

  return {
    title,
    description,
    alternates: {
      canonical,
      // M9-GEO: advertise the markdown rendition served by
      // app/blog/[slug]/raw.md/route.ts. LLM crawlers honoring the
      // llmstxt.org spec follow this <link rel="alternate"> to fetch
      // a clean markdown version instead of scraping the HTML page.
      types: { 'text/markdown': markdownAlternate },
    },
    openGraph: {
      title,
      description,
      type: 'article',
      url: canonical,
      images: [{ url: ogImage, width: 1200, height: 630, alt: title }],
      publishedTime: post.published_at ?? undefined,
      modifiedTime: post.updated_at,
      authors: post.author_url ? [post.author_url] : [post.author_name],
      tags: post.tags,
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [ogImage],
    },
  }
}

export default async function BlogPostPage({ params }: BlogPostPageProps) {
  const { slug } = await params
  const region = resolveRegion(await headers())

  // Returns null for drafts AND missing posts; both surface as 404 so we
  // never leak draft existence to the public.
  const post = await getPostBySlug(slug, region)
  if (!post) notFound()

  // M4: batch-fetch every image row referenced by the post (cover +
  // inline image blocks) in one round-trip so PostView can render via
  // next/image without N+1 queries.
  const imageIds = collectImageIds(post.content_json, post.cover_image_id)
  const imageMap = await getImagesByIds(imageIds)
  const resolveImage = (id: string) => imageMap.get(id) ?? null

  // M5-core: inline JSON-LD as <script> tags. Same pattern as
  // app/page.tsx organizationSchema. Article + BreadcrumbList are
  // unconditional. M9-AEO: FAQPage / HowTo / Speakable each emit only when
  // the post carries the relevant content (faq blocks / 3+ step-role
  // blocks / tldr|intro role); the builders return null otherwise so we
  // never render an empty <script>.
  const article = articleSchema({ post })
  const breadcrumb = breadcrumbSchema({ post })
  const faqPage = faqPageSchema(post)
  const howTo = howToSchema(post)
  const speakable = speakableSchema(post)

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(article) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumb) }}
      />
      {faqPage && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(faqPage) }}
        />
      )}
      {howTo && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(howTo) }}
        />
      )}
      {speakable && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(speakable) }}
        />
      )}

      <Nav />
      <main className="bg-bg pt-[80px]">
        <PostView post={post} resolveImage={resolveImage} withToc />
      </main>
    </>
  )
}

function collectImageIds(blocks: Block[], cover: string | null): string[] {
  const seen = new Set<string>()
  if (cover) seen.add(cover)
  for (const b of blocks) {
    if (b.type === 'image' && b.data.imageId) seen.add(b.data.imageId)
  }
  return Array.from(seen)
}
